name: PA1

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: assignments/PA1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Compile
      run: make
    - name: Run tests
      run: make test
